# Site wide configuration

title: Geek Out
locale: pt_BR
description: O podcast para geeks conectad@s
logo: geekout_round_300x300.png
search: false
url:


# Jekyll configuration

permalink:   /:year/:month/:day/:title.html
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "bin"]

# iTunes specific configs
itunes:
  subtitle: "O podcast para geeks conectad@s"
  summary: "Seu podcast semanal sobre cultura geek, com dicas de livros, filmes, séries e lugares geeks, tudo para você se divertir e aprender"
  url: https://itunes.apple.com/br/podcast/geek-out/id956387481
  big_image: "/images/geekout-logo-1400x1400.jpg"
  default_image: "/images/geekout_round_300x300.png"
  language: pt-br
  category: "Society &amp; Culture"
base_url: http://geekout.fm

# Site owner
owner:
  name: "Alda Rocha, Rodrigo Franco, Rafael Rosa"
  avatar: bio-photo.jpg
  email: contato@geekout.fm
  disqus-shortname: geekoutfm
  twitter: geekoutfm
  facebook: geekoutfm
  google:
    plus: #username
    analytics: UA-58262329-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
